databases:
  - name: deployment
    databaseName: deployment
    user: deployment

services:
  - type: web
    name: deployment
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn deployment.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: deployment
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4